### ISSUE TITLE
multiple chrome processes spawned after each run

### ISSUE THREAD

**Issue by joe81tx** [stephanlensky/zendriver#33]
Hi,
After each successful run 3 additional chrome processes are created, so if I run the script 10 times I'll have 30 chrome processes running.
ps aux | grep chrome
joe        63375   0.0  1.8  527292 306640  0  I    17:25       0:01.04 chrome: --type=gpu-process --disable-breakpad --headless=new --ozone-platform=headless --
joe        63376   0.0  1.4  358512 227956  0  I    17:25       0:00.33 chrome: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --ser
joe        63377   0.0  1.4  355796 226564  0  I    17:25       0:00.16 chrome: --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --ser

Operating system=FreeBSD 14.2
Chrome version=131.0.6778.139

Code:
import asyncio
import zendriver as zd

async def main():
    browser = await zd.start(
        headless=True,
        browser_executable_path="/usr/local/bin/chrome",
    )
    page = await browser.get("https://www.google.com")
    await page.close()
    await browser.stop()
if __name__ == "__main__":
    zd.loop().run_until_complete(main())

**Comment by mighty-phoenix** [comment]
+1

**Comment by stephanlensky** [comment]
I'm not able to replicate this on Debian 12 with Google Chrome 131.0.6778.204.

@joe81tx @mighty-phoenix any assistance in debugging this would be much appreciated.

There is a hook [here](https://github.com/stephanlensky/zendriver/blob/main/zendriver/core/browser.py#L95-L100) which should kill Chrome when the script exits. The actual logic for `stop()` is [here](https://github.com/stephanlensky/zendriver/blob/main/zendriver/core/browser.py#L566-L589), and I'm not sure why it wouldn't work on FreeBSD.

BTW, you can replace `zd.loop().run_until_complete(main())` with `asyncio.run(main())`. I'm not sure why nodriver recommended doing things that way instead of using the standard library method.

**Comment by joe81tx** [comment]
I ran the sample code I provided above on a fedora 41 vm and did not have any lingering chrome processes so it does seem specific to FreeBSD. Python 3.11 is the latest version available on the platform and as I understand it they do a lot of work and massaging to get a new version supported. I am very grateful for your software, it was the only solution I found that was able to get around cloudflare and didn't require an OS specific browser download which would ultimately fail on FreeBSD. BTW, I don't think it matters but the browser I'm using is chromium, the official google chrome isn't available for this OS. I also get the same results with ungoogled chromium.

I don't know any real programming so I'm happy to try suggestions if you can provide instructions but don't have the background to debug further on my own. I looked at the stop and browser_atexit links you provided but don't think there's anything I can implement from them. I ended up using a bash script that runs via cron right after the python code to pkill -f "chrome" and that prevents me from being overrun with orphaned processes. I would like to find a real fix though since I worry if I implement more scraping jobs one might overlap with the kill command even if I only run it once a day.

I originally tried asyncio.run(main()) but it gives me the messages below, the run_until_complete way doesn't generate any messages. I just confirmed that either way I get the same 3 lingering chrome processes after a run.
```
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x2cce61ca9f80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
    self._close(None)
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 762, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by stephanlensky** [comment]
Very weird. It does seem like the issue is probably specific to FreeBSD then. I'm also not sure why `asyncio.run` isn't working for you.

> I don't know any real programming so I'm happy to try suggestions if you can provide instructions but don't have the background to debug further on my own.

No problem, totally understandable.

Maybe I will try to boot up a FreeBSD VM sometime in the future and see if I can replicate, I'm not sure when I'll get around to it though.

One thought, have you considered running in Docker? It may be a bit more involved without a programming background, but that might help solve some of the issues. I have a Debian-based Docker project template at [`stephanlensky/zendriver-docker`](https://github.com/stephanlensky/zendriver-docker) which may be helpful to you.

**Comment by C0uchP0tat0** [comment]
Hello everyone.

I encountered a similar issue with Ubuntu + Docker + Python 3.11.11. A single browser launch spawns multiple processes, and await browser.stop() doesn’t always terminate all of them—especially noticeable when scraping a large number of pages.

To work around this, I extract the browser’s PID (pid = browser._process_pid) and then forcefully kill all child processes:

```
parent = psutil.Process(pid)
for child in parent.children(recursive=True):
    child.kill()
```

**Comment by joe81tx** [comment]
Thanks for this information @C0uchP0tat0!
Perhaps it's not a FreeBSD thing but a python 3.11 thing. Anytime I tried it on linux it worked but I would've been running the latest version available on the distro so 3.12 or 3.13. I like your workaround much more than mine but it wasn't working on FreeBSD. I almost gave up but tried also killing the parent and it successfully removed all chrome processes. Thank you both again!

```
    pid = browser._process_pid
    parent = psutil.Process(pid)
    for child in parent.children(recursive=True):
        child.kill()
    parent.kill()
```
