### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by abediaga** [stephanlensky/zendriver#9]
AttributeError: 'tuple' object has no attribute 'value'
/home/abediaga_env/lib/python3.12/site-packages/zendriver/core/util.py:145: RuntimeWarning: coroutine 'Browser.stop' was never awaited
  _.stop()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7dad37034b80>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 126, in __del__
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 104, in close
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 568, in close
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 592, in _close
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
RuntimeError: Event loop is closed

![Sin título](https://github.com/user-attachments/assets/2dcdf90b-c3d1-49c6-bc98-ee4904233ab6)

**Comment by stephanlensky** [comment]
Hi, not sure how to help with so little information. Please see: https://github.com/stephanlensky/zendriver/blob/main/CONTRIBUTING.md#reporting-bugs

At the very least, I need to see your code to be able to help.

Please give the link ^ a read and feel free to open a new issue with the required information once you're ready.
